import streamlit as st

st.title("Blue Archive character's voice CNN model")
st.write("")
st.write("")
st.title("Dataset")
st.write("This dataset contain character's audio from Blue Archive game")
st.write("and I have to download each files one by one")
st.write("")
st.write("My dataset contains 24 unique characters")
st.write("and each character have 20-35 audio files")
st.write("Totally I have 653 audio files for this dataset")
st.write("All of them are .mp3 files and are converted into .wav files using Librosa library")
st.write("After that, the .wav files are converted from time-domain to frequency-domain using MFCC")
st.write("with sample rate of 48000 sample per second, each for 3 seconds and using MFCC coefficients as 128")
st.write("Dataset's source: https://bluearchive.wiki/wiki/Category:Characters_audio")
st.write("")
st.write("")
st.title("Feature explaination")
st.write("**Character's name(target)**")
st.write("The name of the character in the audio file")
st.write("**MFCC**")
st.write("Mel-frequency cepstral coefficients (MFCCs) are coefficients that collectively make up an MFC.")
st.write("They are derived from a type of cepstral representation of the audio clip.")
st.write("(A nonlinear 'spectrum-of-a-spectrum')")
st.write("")
st.write("")
st.title("CNN")
st.write("Input layer(Flatten) change input shape to 128x1x1")
st.write("There are 3 hidden layers, each layer has 1024, 1024, 512 perceptrons respectively")
st.write("All of them have BatchNormalization dropout 0.5 and use activation funtion='LeakyReLU' with alpha 0.1")
st.write("Lastly, the output layer uses activation funtion='softmax' with 24 perceptrons(24 characters)")
st.write("")
st.write("")
st.write("This model can predict only some of the characters in the game")
st.title("Here is the list of the characters")
st.write("1.Kurimura Airi")
st.write("2.Murokasa Akane")
st.write("3.Wanibuchi Akari")
st.write("4.Amau Ako")
st.write("5.Tendou Alice")
st.write("6.Rikuhachima Aru")
st.write("7.Ichinose Asuna")
st.write("8.Hakari Atsuko")
st.write("9.Okusora Ayane")
st.write("10.Shirasu Azusa")
st.write("11.Renkawa Cherino")
st.write("12.Motomiya Chiaki")
st.write("13.Izumimoto Eimi")
st.write("14.Nemugaki Fubuki")
st.write("15.Aikiyo Fuuka")
st.write("16.Akashi Junko")
st.write("17.Ushimaki Juri")
st.write("18.Asahina Pina")
st.write("19.Kayama Reijo")
st.write("20.Uzawa Reisa")
st.write("21.Fuwa Renge")
st.write("22.Tsukatsuki Rio")
st.write("23.Akeshiro Rumi")
st.write("24.Kozeki Ui")