import streamlit as st

st.title("cnnData.py")
st.write("this is cnnData.py")
st.write("")
st.write("")
st.title("Dataset")
st.write("This dataset is from Blue Archive wiki")
st.write("by the way this dataset is a character's audio")
st.write("so I have to download one by one files")
st.write("")
st.write("my dataset contains 24 characters' audio")
st.write("and each characters have 20-35 audio files")
st.write("so totally I have 653 audio files for this dataset")
st.write("by the way all of them are .mp3 files and I have to convert them into .wav files")
st.write("by librosa library one by one and map name of charector in another valiable") 
st.write("and then I convert .wav files into mfcc features ")
st.write("with sample rate 48000 MFCC coefficients 120 and duration 3 seconds")
st.write("Dataset's source: https://bluearchive.wiki/wiki/Category:Characters_audio")
st.write("")
st.write("")
st.title("Feature expantion")
st.write("")
st.write("")
st.title("CNN")
st.write("Input layer(Flatten) change input shape to 128x1x1")
st.write("hidden layer are 3 layer, first second have 1024 and third layer have 512 perceptrons")
st.write("3 of them have BatchNormalization dropout 0.5 and use activation='LeakyReLU' with alpha 0.1")
st.write("and lastly output layer use activation='softmax' with 24 perceptrons(24 characters)")

st.write("explain whitch charector")