import streamlit as st

st.title("cnnData.py")
st.write("this is cnnData.py")
st.write("")
st.write("")
st.title("Dataset")
st.write("This dataset is a character's audio from Blue Archive wiki")
st.write("and I have to download each files one by one")
st.write("")
st.write("my dataset contains 24 characters' audio")
st.write("and each characters have 20-35 audio files")
st.write("so totally I have 653 audio files for this dataset")
st.write("by the way all of them are .mp3 files and I have to convert them into .wav files")
st.write("by librosa library one by one and map name of charector in another valiable") 
st.write("and then I convert .wav files into mfcc features")
st.write("with sample rate 48000 sample per second, sample for 3 seconds and MFCC coefficients 120")
st.write("Dataset's source: https://bluearchive.wiki/wiki/Category:Characters_audio")
st.write("")
st.write("")
st.title("Feature expantion")
st.write("")
st.write("")
st.title("CNN")
st.write("Input layer(Flatten) change input shape to 128x1x1")
st.write("hidden layer are 3 layer, first second have 1024 and third layer have 512 perceptrons")
st.write("3 of them have BatchNormalization dropout 0.5 and use activation='LeakyReLU' with alpha 0.1")
st.write("and lastly output layer use activation='softmax' with 24 perceptrons(24 characters)")
st.write("")
st.write("")
st.write("explain whitch charector")
st.title("To use this model")
st.write("explain whitch charector")
st.write("1.Kurimura Airi")
st.write("2.Murokasa Akane")